### ISSUE TITLE
attempt to perform arithmetic on local 'space' (a nil value)

### ISSUE THREAD

**Issue by tchncs** [minetest-mods/irc#26]
Hi there, i just noticed the following error on minetest startup:

```
worldmods/irc/irc/messages.lua:100: attempt to perform arithmetic on local 'space' (a nil value)
stack traceback:
       worldmods/irc/irc/messages.lua:100: in function 'fromRFC1459'
       worldmods/irc/irc/messages.lua:12: in function 'Message'
       worldmods/irc/irc/init.lua:174: in function 'think'
       irc/init.lua:85: in function <worldmods/irc/init.lua:85>
        [C]: in function 'xpcall'
        worldmods/irc/init.lua:85: in function <worldmods/irc/init.lua:74>
       /home/minetest/minetest/bin/../builtin/game/register.lua:369: in function </home/minetest/minetest/bin/../builtin/game/register.lua:349>
```

The mod, and minetest are working but i guess it wouldn't be wrong to report it anyway. :)

`Lua 5.1.5`

**Comment by sofar** [comment]
That would be a bug in https://github.com/ShadowNinja/LuaIRC and not this mod (note the git submodule!).

@ShadowNinja ?

**Comment by ShadowNinja** [comment]
It seems like the server is sending `":server.example.net\r\n"` with no actual message, which I believe is illegal according to RFC 1459.  Does this occur on every startup?  And if so, what ircd/network are you using?  Please set `irc.debug = true` and see what it prints just before it crashes.

Related: #19.

**Comment by kaeza** [comment]
@tchncs Any news?

**Comment by kaeza** [comment]
@tchncs ?

**Comment by tchncs** [comment]
No, i am sorry - i am not a developer yet and only able to figure out stuff 'til a specific level. 😖

**Comment by kaeza** [comment]
@tchncs See ShadowNinja's comment. Can you provide that info?

**Comment by tchncs** [comment]
I am sorry for my late answers, so busy these days. :/ 
It seems to not happen every time - i just got this on one world where the debug setting wasn't set and i was unable to reproduce trying on two worlds. Not that handy. :/
But i will give feedback with debug again as soon as this happen again.

**Comment by kaeza** [comment]
I will close this as it is surely an ircd/LuaIRC issue and nothing can be done from here.
