### ISSUE TITLE
allow users to disable chat from external server

### ISSUE THREAD

**Issue by tchncs** [minetest-mods/irc#27]
Hi there, 

it would be awesome if a user can control if all the server chats are visible or only the one from the current server.

**Comment by ShadowNinja** [comment]
I believe you're looking for the `/part` and `/join` commands.  They're provided when you set `irc.enable_player_part = true`.

**Comment by tchncs** [comment]
Oh, i thought i already closed this - i forgot for one second that the second chat is streaming from the irc into the first chat.

Wonderful thank you really much, i thought this isn't even possible but just tested it with the wanted result!
