### ISSUE TITLE
SSL support?

### ISSUE THREAD

**Issue by YuGiOhJCJ** [minetest-mods/irc#30]
Hello,

I would like to know if the irc mod supports SSL.

From what I can grep in the code, I would say that the answer is negative:
```
$ grep -r "ssl"
irc/init.lua:		local work, ssl = pcall(require, "ssl")
irc/init.lua:		s = ssl.wrap(s, params)
$ grep -r "SSL"
```

But is there any chance to have SSL support soon?

Lots of IRC clients support connection through SSL (qwebirc, xchat, ...) and my IRC server only accepts SSL connections so unfortunately I can't use your Minetest mod because of that.

Thank you.
Best regards.

**Comment by ShadowNinja** [comment]
As your snippet shows, SSL is supported.  You just have to install [LuaSec](https://luarocks.org/modules/brunoos/luasec) somewhere where the IRC mod can find it and set `irc.secure = true`.

**Comment by YuGiOhJCJ** [comment]
Wow it works! Thank you. Problem solved.
