### ISSUE TITLE
IRC mod breaks with mod security enabled

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/irc#31]
See here: https://forum.minetest.net/viewtopic.php?f=47&t=15842&view=unread#p239267

(I have not verified this, I am just repeating what addi said.)

**Comment by kaeza** [comment]
I cannot reproduce the issue with `module` using the current Minetest HEAD (c05aac3766e88530fcf5d38a8c25c994b792b324 at time of writing).

I was able to fix a related issue with `require` though, which I just pushed.

Can someone confirm the issue?

**Comment by kaeza** [comment]
Should be fixed by https://github.com/minetest-mods/irc/commit/3e2d98f9ef1504c6121f3d9832df1a7138bf8780. If not, please bump this and I will reopen.
