### ISSUE TITLE
Refused messages are sent though the irc

### ISSUE THREAD

**Issue by tchncs** [minetest-mods/irc#33]
Hi there, i just tested [the new spamcontrol feature](https://github.com/minetest/minetest/commit/d4c76258e37337ea585cf24d8e05b50a30fa307d) of Minetest.
It turns out that successful refused messages are sent by the IRC mod anyway.

**Comment by kaeza** [comment]
I can confirm the issue, but IMHO it is a ~~bug~~ feature of the engine.

IRC mod is just blindly processing chat messages; it should be the engine's job to not send filtered messages to mods.

**Comment by ShadowNinja** [comment]
Definitely an engine issue seeing as we have no way of knowing if a message was filtered -- other than copying all of the spam filtering code into the mod and running it ourselves to see what would happen.
