### ISSUE TITLE
The irc.NSPass setting is not used

### ISSUE THREAD

**Issue by YuGiOhJCJ** [minetest-mods/irc#35]
Hello,
In my minetest.conf configuration file, I add this last line:
```
irc.NSPass = PASS
```
With _PASS_ corresponding to the real password of my registered nick.
However, when I am reading the logs on my IRC server [1], I see that my bot does not use the NickServ IDENTIFY command.
That's weird because when I check your mod [2] source code, it seems that you correctly handles the thing:
```
$ grep -r "NSPass"
README.md:  * `irc.NSPass` (string, default nil)
init.lua:	if self.config.NSPass then
init.lua:		self:say("NickServ", "IDENTIFY "..self.config.NSPass)
config.lua:setting("string", "NSPass") -- NickServ password
```
Of course, I have no problem to identify my bot outside of Minetest (for example through the HexChat IRC client).
Can you help me to identify my bot please?
Thank you.
Best regards.

[1] ircd-hybrid 8.2.20 with anope 2.0.4
[2] minetest-irc 0c47e10a908c189dd0bf2b0d058a3b7163e60e28

**Comment by kaeza** [comment]
I have located the problem, and will push a fix shortly.

**Comment by kaeza** [comment]
Tested on Freenode and seems to be fixed.

Please bump if this does not fix the issue.

**Comment by YuGiOhJCJ** [comment]
Thanks I approve it works fine now.
