### ISSUE TITLE
Username for connection

### ISSUE THREAD

**Issue by joenas** [minetest-mods/irc#42]
Hi there!

Is there any particular reason why the [username](https://github.com/minetest-mods/irc/blob/master/init.lua#L140) isn't the same as the configured nick? Or at least its own setting? 

Cheers

**Comment by tacotexmex** [comment]
`realname` should probably be configurable too.

**Comment by ShadowNinja** [comment]
Having a consistent username is useful for distinguishing Minetest servers from users in a channel with both.  Having the username be the nick doesn't provide any useful information, wheres having something like `"Minetest"` does.

Having a setting with a default value seems perfectly reasonable though.

**Comment by kaeza** [comment]
Closing this as #43 was merged.
