### ISSUE TITLE
[Feature Request] Colored IRC nick-names to be displayed in-game

### ISSUE THREAD

**Issue by ClobberXD** [minetest-mods/irc#45]
Currently all the text is white (non-colorized), and in-game players might not notice if they aren't already actively chatting. So, it'd be nice to see colored IRC nicks in game (just the \<name@IRC\> part); or the whole message can be fully colored too.

**Comment by mckaygerhard** [comment]
it seems this was merged with commit "Add support for configurable coloring of IRC messages in-game" at   https://github.com/minetest-mods/irc/commit/b4fbccd64ac758ee698f4f741250e9b682903363 using PR #52 so should be closed

**Comment by magnetar47** [comment]
Oh yes, this needs to be closed. Sorry. @sofar?
